[error] java.io.IOException: Could not create directory G:\My Drive\scala-study\practice\project\target\streams\runtime\unmanagedJars\_global\streams: java.nio.file.FileAlreadyExistsException: G:\My Drive\scala-study\practice\project\target\streams
[error] 	at sbt.io.IO$.createDirectory(IO.scala:336)
[error] 	at sbt.io.IO$.$anonfun$touch$2(IO.scala:314)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] 	at sbt.io.IO$.touch(IO.scala:312)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:196)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:163)
[error] 	at sbt.Classpaths$.exportClasspath(Defaults.scala:2083)
[error] 	at sbt.Classpaths$.$anonfun$exportClasspath$2(Defaults.scala:2081)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] Caused by: java.nio.file.FileAlreadyExistsException: G:\My Drive\scala-study\practice\project\target\streams
[error] 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
[error] 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
[error] 	at java.base/sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:509)
[error] 	at java.base/java.nio.file.Files.createDirectory(Files.java:692)
[error] 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:799)
[error] 	at java.base/java.nio.file.Files.createDirectories(Files.java:785)
[error] 	at sbt.io.IO$.$anonfun$createDirectory$1(IO.scala:332)
[error] 	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] 	at sbt.io.IO$.createDirectory(IO.scala:334)
[error] 	at sbt.io.IO$.$anonfun$touch$2(IO.scala:314)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.internal.io.Retry$.liftedTree2$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.impl$1(Retry.scala:38)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:52)
[error] 	at sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] 	at sbt.io.IO$.touch(IO.scala:312)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:196)
[error] 	at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:163)
[error] 	at sbt.Classpaths$.exportClasspath(Defaults.scala:2083)
[error] 	at sbt.Classpaths$.$anonfun$exportClasspath$2(Defaults.scala:2081)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:835)
[error] (Runtime / unmanagedJars) java.io.IOException: Could not create directory G:\My Drive\scala-study\practice\project\target\streams\runtime\unmanagedJars\_global\streams: java.nio.file.FileAlreadyExistsException: G:\My Drive\scala-study\practice\project\target\streams
